
export const TAKE_COURSE_DATA = "TAKE_COURSE_DATA"
export const TAKE_AUTHOR_DATA = "TAKE_AUTHOR_DATA"
export const TAKE_BOOK_DATA = "TAKE_BOOK_DATA"
export const TAKE_BOOK_INFO_DATA = "TAKE_BOOK_INFO_DATA"
export const TAKE_CATEGORY_DATA = "TAKE_CATEGORY_DATA"
export const TAKE_USER_DATA = "TAKE_USER_DATA"
export const TAKE_USER_COURSE_DATA = "TAKE_USER_COURSE_DATA"
export const TAKE_COURSE_PARTS_DATA = "TAKE_COURSE_PARTS_DATA"